<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>
            Clc
        </title>
        <link rel="stylesheet" href="style.css" />
    </head>
    <body id="cv">
        <header>
            <h1>Result</h1>
            <fieldset><? php echo $result; ?></fieldset>
        </header>
        <main>
            <section>
                <h2>Opération</h2>
                <form ation="index.php" method="post">
                <fieldset>
                    <label for="nbr1">Choisissez votre premier Nombre</label>
                        <input type="number" id="nbr1" name="firstnbr"><br>
                    <label for="nbr2">Choisissez Votre second Nombre</label>
                        <input type="number" id="nbr2" name="secondnbr">
                </fieldset>
                <fieldset>
                    <label for="oeration-select">Choisissez votre opération</label>
                    <select name="operations" id="operation-select">
                        <option value="add">Addition</option>
                        <option value="substract">Soustration</option>
                        <option value="multiply">Multiplication</option>
                        <option value="divide">Diviser</option>
                        <option value="modulo">Modulo</option>
                    </select>
                </fieldset>
                <fieldset>
                    <input type="submit" id="btn-result" value="Calculer">
                </fieldset>
            </section>
        </main>
        <footer>
        </footer>
    </body>
</html>